name: flutter_mobigic
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
#  follows Semantic Versioning [Major_Version.Minor_Version.Patch_Version.Build_Metadata]
  # Major: Breaking changes
  # Minor: New features, backward-compatible
  # Patch: Bug fixes, backward-compatible
  # Build Metadata: Additional build information 

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  very_good_analysis: ^9.0.0
  intl: ^0.20.2
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/